/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Adana;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author IlyuShin
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        Tampil_Jam();
        Tampil_Tanggal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jl_tanggal = new javax.swing.JLabel();
        jl_jam = new javax.swing.JLabel();
        jl_home = new javax.swing.JLabel();
        jl_datacustomer = new javax.swing.JLabel();
        jl_updateadmin = new javax.swing.JLabel();
        jl_products = new javax.swing.JLabel();
        jl_category = new javax.swing.JLabel();
        jl_supplier = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jl_close = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(231, 50, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(170, 281));

        jl_tanggal.setBackground(new java.awt.Color(255, 255, 255));
        jl_tanggal.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jl_tanggal.setForeground(new java.awt.Color(255, 255, 255));
        jl_tanggal.setText("Date");

        jl_jam.setBackground(new java.awt.Color(255, 255, 255));
        jl_jam.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jl_jam.setForeground(new java.awt.Color(255, 255, 255));
        jl_jam.setText("Hour");

        jl_home.setBackground(java.awt.Color.white);
        jl_home.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jl_home.setForeground(java.awt.Color.white);
        jl_home.setText("HOME");
        jl_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_homeMouseClicked(evt);
            }
        });

        jl_datacustomer.setBackground(java.awt.Color.white);
        jl_datacustomer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jl_datacustomer.setForeground(new java.awt.Color(243, 153, 153));
        jl_datacustomer.setText("DATA CUSTOMER");
        jl_datacustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_datacustomerMouseClicked(evt);
            }
        });

        jl_updateadmin.setBackground(java.awt.Color.white);
        jl_updateadmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jl_updateadmin.setForeground(new java.awt.Color(243, 153, 153));
        jl_updateadmin.setText("UPDATE ADMIN");
        jl_updateadmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_updateadminMouseClicked(evt);
            }
        });

        jl_products.setBackground(java.awt.Color.white);
        jl_products.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jl_products.setForeground(new java.awt.Color(243, 153, 153));
        jl_products.setText("PRODUCTS");
        jl_products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_productsMouseClicked(evt);
            }
        });

        jl_category.setBackground(java.awt.Color.white);
        jl_category.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jl_category.setForeground(new java.awt.Color(243, 153, 153));
        jl_category.setText("CATEGORY");
        jl_category.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_categoryMouseClicked(evt);
            }
        });

        jl_supplier.setBackground(java.awt.Color.white);
        jl_supplier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jl_supplier.setForeground(new java.awt.Color(243, 153, 153));
        jl_supplier.setText("SUPPLIER");
        jl_supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_supplierMouseClicked(evt);
            }
        });

        btn_logout.setBackground(new java.awt.Color(255, 251, 237));
        btn_logout.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(231, 50, 50));
        btn_logout.setText("LOGOUT");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jl_jam))
                    .addComponent(jl_tanggal)
                    .addComponent(jl_home)
                    .addComponent(jl_datacustomer)
                    .addComponent(jl_products)
                    .addComponent(jl_category)
                    .addComponent(jl_supplier)
                    .addComponent(jl_updateadmin)
                    .addComponent(btn_logout))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jl_tanggal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_jam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jl_home)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_datacustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_updateadmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_products)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_category)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_supplier)
                .addGap(30, 30, 30)
                .addComponent(btn_logout)
                .addGap(15, 15, 15))
        );

        jPanel2.setBackground(new java.awt.Color(255, 251, 237));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 30)); // NOI18N
        jLabel5.setForeground(java.awt.Color.red);
        jLabel5.setText("ADMINISTRATOR");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/administrative_tools_64px_1.png"))); // NOI18N

        jl_close.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jl_close.setForeground(java.awt.Color.red);
        jl_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/close_merah.10px.png"))); // NOI18N
        jl_close.setToolTipText("");
        jl_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 377, Short.MAX_VALUE)
                .addComponent(jl_close)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(78, 78, 78))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_close)
                .addGap(75, 75, 75)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jl_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_closeMouseClicked
        // TODO add your handling code here:
        int jawab = JOptionPane.showOptionDialog(this,"Are You Sure Want to Exit?","Exit",
            JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE, null, null, null);
        if(jawab == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Program Stop");
            System.exit(0);
        }
    }//GEN-LAST:event_jl_closeMouseClicked

    private void jl_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_homeMouseClicked
        // TODO add your handling code here:
        Admin ad = new Admin();
        ad.setVisible(true);
        dispose();
    }//GEN-LAST:event_jl_homeMouseClicked

    private void jl_datacustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_datacustomerMouseClicked
        // TODO add your handling code here:
        DataCustomer dc = new DataCustomer();
        dc.setVisible(true);
        dispose();
    }//GEN-LAST:event_jl_datacustomerMouseClicked

    private void jl_updateadminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_updateadminMouseClicked
        // TODO add your handling code here:
        UpdateAdmin ua = new UpdateAdmin();
        ua.setVisible(true);
        dispose();
    }//GEN-LAST:event_jl_updateadminMouseClicked

    private void jl_productsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_productsMouseClicked
        // TODO add your handling code here:
        Products pro = new Products();
        pro.setVisible(true);
        dispose();
    }//GEN-LAST:event_jl_productsMouseClicked

    private void jl_categoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_categoryMouseClicked
        // TODO add your handling code here:
        Category ca = new Category();
        ca.setVisible(true);
        dispose();
    }//GEN-LAST:event_jl_categoryMouseClicked

    private void jl_supplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_supplierMouseClicked
        // TODO add your handling code here:
        Supplier su = new Supplier();
        su.setVisible(true);
        dispose();
    }//GEN-LAST:event_jl_supplierMouseClicked

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        int jawab = JOptionPane.showOptionDialog(this,"Are You Sure Want to Logout?","Logout",
            JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE, null, null, null);
        if(jawab == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Back To Login");
            LoginAdmin la = new LoginAdmin();
            la.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }
    
    public Admin(String username){
        initComponents();
    }
    
    public void Tampil_Jam(){
        ActionListener taskPerformer = new ActionListener() {
        @Override
            public void actionPerformed(ActionEvent evt) {
            String nol_jam = "", nol_menit = "",nol_detik = "";
 
            java.util.Date dateTime = new java.util.Date();
            int nilai_jam = dateTime.getHours();
            int nilai_menit = dateTime.getMinutes();
            int nilai_detik = dateTime.getSeconds();
 
            if(nilai_jam <= 9) nol_jam= "0";
            if(nilai_menit <= 9) nol_menit= "0";
            if(nilai_detik <= 9) nol_detik= "0";
 
            String jam = nol_jam + Integer.toString(nilai_jam);
            String menit = nol_menit + Integer.toString(nilai_menit);
            String detik = nol_detik + Integer.toString(nilai_detik);
 
            jl_jam.setText(jam+":"+menit+":"+detik+"");
            }
        };
    new Timer(1000, taskPerformer).start();
    }   
 
public void Tampil_Tanggal() {
    java.util.Date tglsekarang = new java.util.Date();
    SimpleDateFormat smpdtfmt = new SimpleDateFormat("dd MMMMMMMMM yyyy", Locale.getDefault());
    String tanggal = smpdtfmt.format(tglsekarang);
    jl_tanggal.setText(tanggal);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_logout;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jl_category;
    private javax.swing.JLabel jl_close;
    private javax.swing.JLabel jl_datacustomer;
    private javax.swing.JLabel jl_home;
    private javax.swing.JLabel jl_jam;
    private javax.swing.JLabel jl_products;
    private javax.swing.JLabel jl_supplier;
    private javax.swing.JLabel jl_tanggal;
    private javax.swing.JLabel jl_updateadmin;
    // End of variables declaration//GEN-END:variables
}
