/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Adana;

import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author IlyuShin
 */
public class Category extends javax.swing.JFrame {

    /**
     * Creates new form Category
     */
    public Category() {
        initComponents();
        isidatacategory();
        Tampil_Jam();
        Tampil_Tanggal();
    }

Connection Con = null;
Statement St = null;
ResultSet Rs = null;
PreparedStatement Pst = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jl_tanggal = new javax.swing.JLabel();
        jl_jam = new javax.swing.JLabel();
        jl_home = new javax.swing.JLabel();
        jl_datacustomer = new javax.swing.JLabel();
        jl_updateadmin = new javax.swing.JLabel();
        jl_products = new javax.swing.JLabel();
        jl_category = new javax.swing.JLabel();
        jl_supplier = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_catname = new javax.swing.JTextField();
        tf_catid = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_list = new javax.swing.JTable();
        jl_close = new javax.swing.JLabel();
        tf_desc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(231, 50, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(170, 500));

        jl_tanggal.setBackground(new java.awt.Color(255, 255, 255));
        jl_tanggal.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jl_tanggal.setForeground(new java.awt.Color(255, 255, 255));
        jl_tanggal.setText("Date");

        jl_jam.setBackground(new java.awt.Color(255, 255, 255));
        jl_jam.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jl_jam.setForeground(new java.awt.Color(255, 255, 255));
        jl_jam.setText("Hour");

        jl_home.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jl_home.setForeground(new java.awt.Color(243, 153, 153));
        jl_home.setText("HOME");
        jl_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_homeMouseClicked(evt);
            }
        });

        jl_datacustomer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jl_datacustomer.setForeground(new java.awt.Color(243, 153, 153));
        jl_datacustomer.setText("DATA CUSTOMER");
        jl_datacustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_datacustomerMouseClicked(evt);
            }
        });

        jl_updateadmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jl_updateadmin.setForeground(new java.awt.Color(243, 153, 153));
        jl_updateadmin.setText("UPDATE ADMIN");
        jl_updateadmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_updateadminMouseClicked(evt);
            }
        });

        jl_products.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jl_products.setForeground(new java.awt.Color(243, 153, 153));
        jl_products.setText("PRODUCTS");
        jl_products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_productsMouseClicked(evt);
            }
        });

        jl_category.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jl_category.setForeground(java.awt.Color.white);
        jl_category.setText("CATEGORY");
        jl_category.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_categoryMouseClicked(evt);
            }
        });

        jl_supplier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jl_supplier.setForeground(new java.awt.Color(243, 153, 153));
        jl_supplier.setText("SUPPLIER");
        jl_supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_supplierMouseClicked(evt);
            }
        });

        btn_logout.setBackground(new java.awt.Color(255, 251, 237));
        btn_logout.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(231, 50, 50));
        btn_logout.setText("LOGOUT");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jl_home)
                    .addComponent(jl_datacustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl_products)
                    .addComponent(jl_category)
                    .addComponent(jl_supplier)
                    .addComponent(jl_updateadmin)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jl_jam))
                            .addComponent(jl_tanggal)))
                    .addComponent(btn_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jl_tanggal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_jam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jl_home)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_datacustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_updateadmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_products)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_category)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_supplier)
                .addGap(135, 135, 135)
                .addComponent(btn_logout)
                .addGap(16, 16, 16))
        );

        jPanel2.setBackground(new java.awt.Color(255, 251, 237));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(231, 50, 50));
        jLabel2.setText("MANAGE CATEGORIES");

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel1.setText("CATEGORY ID");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("CATEGORY NAME");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("DESCRIPTION");

        tf_catname.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N

        tf_catid.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N

        btn_add.setBackground(new java.awt.Color(231, 50, 50));
        btn_add.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_add.setForeground(java.awt.Color.white);
        btn_add.setText("ADD");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_edit.setBackground(new java.awt.Color(231, 50, 50));
        btn_edit.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_edit.setForeground(java.awt.Color.white);
        btn_edit.setText("EDIT");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(231, 50, 50));
        btn_delete.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_delete.setForeground(java.awt.Color.white);
        btn_delete.setText("DELETE");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_clear.setBackground(new java.awt.Color(231, 50, 50));
        btn_clear.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_clear.setForeground(java.awt.Color.white);
        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(231, 50, 50));
        jLabel8.setText("CATEGORIES LIST");

        tb_list.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tb_list.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        tb_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CATEGORY ID", "CATEGORY NAME", "DESCRIPTION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_list.setShowGrid(true);
        tb_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_listMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_list);

        jl_close.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jl_close.setForeground(java.awt.Color.red);
        jl_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/close_merah.10px.png"))); // NOI18N
        jl_close.setMaximumSize(new java.awt.Dimension(28, 28));
        jl_close.setMinimumSize(new java.awt.Dimension(28, 28));
        jl_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_closeMouseClicked(evt);
            }
        });

        tf_desc.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jl_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(tf_catid, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel3))
                                            .addComponent(tf_desc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_catname, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2)))
                            .addComponent(jLabel1))
                        .addGap(0, 37, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jl_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_catid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(tf_catname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_edit)
                    .addComponent(btn_delete)
                    .addComponent(btn_clear)
                    .addComponent(btn_add))
                .addGap(29, 29, 29)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        if(tf_catid.getText().isEmpty()|| tf_catname.getText().isEmpty()|| tf_desc.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Fill all the Fields");
        }
        else{
            try{
                Con = (Connection) (DriverManager.getConnection("jdbc:mysql://localhost:3306/adanadb","root",""));
                PreparedStatement add = Con.prepareStatement("insert into category(catid,catname,description) values (?,?,?)");
                add.setString(1, tf_catid.getText());
                add.setString(2, tf_catname.getText());
                add.setString(3, tf_desc.getText());
                int row = add.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data added Successfully"); 
                tf_catid.setText("");
                tf_catname.setText("");
                tf_desc.setText("");
                tf_catid.requestFocus();
                isidatacategory();
            }catch(SQLException e){
            }
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tb_list.getModel();
        int selectedIndex = tb_list.getSelectedRow();
        if(tf_catid.getText().isEmpty()|| tf_catname.getText().isEmpty()|| tf_desc.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Fill all the Fields");
        }
        else{
            try{
                int id = Integer.parseInt(model.getValueAt(selectedIndex, 0).toString());
                Con = (Connection) (DriverManager.getConnection("jdbc:mysql://localhost:3306/adanadb","root",""));
                Pst = Con.prepareStatement("Update adanadb.category set catname=?, description=? where catid=?");
                Pst.setString(1, tf_catname.getText());
                Pst.setString(2, tf_desc.getText());
                Pst.setInt(3, id);
                Pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Updated Successfully");
                isidatacategory();
            }catch(SQLException e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tb_list.getModel();
        int selectedIndex = tb_list.getSelectedRow();
        if(tf_catid.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Select the Data You Want to Delete");
        }
        else{
            try{
                int id = Integer.parseInt(model.getValueAt(selectedIndex, 0).toString());
                Con = (Connection) (DriverManager.getConnection("jdbc:mysql://localhost:3306/adanadb","root",""));
                Pst = Con.prepareStatement("Delete from category where catid=?");
                Pst.setInt(1, id);
                Pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Deleted Successfully");
                tf_catid.setText("");
                tf_catname.setText("");
                tf_desc.setText("");
                isidatacategory();
            }catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        tf_catid.setText("");
        tf_catname.setText("");
        tf_desc.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed

    private void tb_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_listMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tb_list.getModel();
        int Myindex = tb_list.getSelectedRow();
        tf_catid.setText(model.getValueAt(Myindex, 0).toString());
        tf_catname.setText(model.getValueAt(Myindex, 1).toString());
        tf_desc.setText(model.getValueAt(Myindex, 2).toString());
    }//GEN-LAST:event_tb_listMouseClicked

    private void jl_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_homeMouseClicked
        // TODO add your handling code here:
        Admin ad = new Admin();
        ad.setVisible(true);
        dispose();
    }//GEN-LAST:event_jl_homeMouseClicked

    private void jl_datacustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_datacustomerMouseClicked
        // TODO add your handling code here:
        DataCustomer dc = new DataCustomer();
        dc.setVisible(true);
        dispose();
    }//GEN-LAST:event_jl_datacustomerMouseClicked

    private void jl_updateadminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_updateadminMouseClicked
        // TODO add your handling code here:
        UpdateAdmin ua = new UpdateAdmin();
        ua.setVisible(true);
        dispose();
    }//GEN-LAST:event_jl_updateadminMouseClicked

    private void jl_productsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_productsMouseClicked
        // TODO add your handling code here:
        Products pro = new Products();
        pro.setVisible(true);
        dispose();
    }//GEN-LAST:event_jl_productsMouseClicked

    private void jl_categoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_categoryMouseClicked
        // TODO add your handling code here:
        Category ca = new Category();
        ca.setVisible(true);
        dispose();
    }//GEN-LAST:event_jl_categoryMouseClicked

    private void jl_supplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_supplierMouseClicked
        // TODO add your handling code here:
        Supplier su = new Supplier();
        su.setVisible(true);
        dispose();
    }//GEN-LAST:event_jl_supplierMouseClicked

    private void jl_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_closeMouseClicked
        // TODO add your handling code here:
        int jawab = JOptionPane.showOptionDialog(this,"Are You Sure Want to Exit?","Exit",
            JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE, null, null, null);
        if(jawab == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Program Stop");
            System.exit(0);
        }
    }//GEN-LAST:event_jl_closeMouseClicked

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        int jawab = JOptionPane.showOptionDialog(this,"Are You Sure Want to Logout?","Logout",
            JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE, null, null, null);
        if(jawab == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Back To Login");
            LoginAdmin la = new LoginAdmin();
            la.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Category().setVisible(true);
            }
        });
    }
    
        public void isidatacategory(){
        int no;
        try{
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/adanadb","root","");
            St = Con.createStatement();
            Rs = St.executeQuery("select * from adanadb.category");
            ResultSetMetaData RSMD = (ResultSetMetaData) Rs.getMetaData();
            no = RSMD.getColumnCount();
            DefaultTableModel DFT = (DefaultTableModel) tb_list.getModel();
            DFT.setRowCount(0);
            while (Rs.next()) {
                Vector v = new Vector();
                for (int i = 1; i <= no; i++) {
                    v.add(Rs.getString("catid"));
                    v.add(Rs.getString("catname"));
                    v.add(Rs.getString("description"));
                }
                DFT.addRow(v);
            }
        } catch (Exception e) {
        }
    }
        
        public Category(String username){
        initComponents();
    }
    
    public void Tampil_Jam(){
        ActionListener taskPerformer = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                String nol_jam = "", nol_menit = "",nol_detik = "";
                java.util.Date dateTime = new java.util.Date();
                int nilai_jam = dateTime.getHours();
                int nilai_menit = dateTime.getMinutes();
                int nilai_detik = dateTime.getSeconds();
                if(nilai_jam <= 9) nol_jam= "0";
                if(nilai_menit <= 9) nol_menit= "0";
                if(nilai_detik <= 9) nol_detik= "0";
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                jl_jam.setText(jam+":"+menit+":"+detik+"");
            }
        };
        new Timer(1000, taskPerformer).start();
    }   
 
    public void Tampil_Tanggal() {
        java.util.Date tglsekarang = new java.util.Date();
        SimpleDateFormat smpdtfmt = new SimpleDateFormat("dd MMMMMMMMM yyyy", Locale.getDefault());
        String tanggal = smpdtfmt.format(tglsekarang);
        jl_tanggal.setText(tanggal);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_logout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jl_category;
    private javax.swing.JLabel jl_close;
    private javax.swing.JLabel jl_datacustomer;
    private javax.swing.JLabel jl_home;
    private javax.swing.JLabel jl_jam;
    private javax.swing.JLabel jl_products;
    private javax.swing.JLabel jl_supplier;
    private javax.swing.JLabel jl_tanggal;
    private javax.swing.JLabel jl_updateadmin;
    private javax.swing.JTable tb_list;
    private javax.swing.JTextField tf_catid;
    private javax.swing.JTextField tf_catname;
    private javax.swing.JTextField tf_desc;
    // End of variables declaration//GEN-END:variables
}
