/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Adana;

import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author IlyuShin
 */
public class Products extends javax.swing.JFrame {

    /**
     * Creates new form Products
     */
    public Products() {
        initComponents();
        isidataproduct();
        GetCat();
        GetSup();
        Tampil_Jam();
        Tampil_Tanggal();
    }
    
Connection Con = null;
Statement St = null;
ResultSet Rs = null;
PreparedStatement Pst = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jl_tanggal = new javax.swing.JLabel();
        jl_jam = new javax.swing.JLabel();
        jl_home = new javax.swing.JLabel();
        jl_datacustomer = new javax.swing.JLabel();
        jl_updateadmin = new javax.swing.JLabel();
        jl_products = new javax.swing.JLabel();
        jl_category = new javax.swing.JLabel();
        jl_supplier = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_proid = new javax.swing.JTextField();
        tf_proname = new javax.swing.JTextField();
        tf_quantity = new javax.swing.JTextField();
        tf_price = new javax.swing.JTextField();
        cb_category = new javax.swing.JComboBox<>();
        btn_add = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_list = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cb_supplier = new javax.swing.JComboBox<>();
        jl_close = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(231, 50, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(170, 256));

        jl_tanggal.setBackground(new java.awt.Color(255, 255, 255));
        jl_tanggal.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jl_tanggal.setForeground(new java.awt.Color(255, 255, 255));
        jl_tanggal.setText("Date");

        jl_jam.setBackground(new java.awt.Color(255, 255, 255));
        jl_jam.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jl_jam.setForeground(new java.awt.Color(255, 255, 255));
        jl_jam.setText("Hour");

        jl_home.setBackground(java.awt.Color.white);
        jl_home.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jl_home.setForeground(new java.awt.Color(243, 153, 153));
        jl_home.setText("HOME");
        jl_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_homeMouseClicked(evt);
            }
        });

        jl_datacustomer.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jl_datacustomer.setForeground(new java.awt.Color(243, 153, 153));
        jl_datacustomer.setText("DATA CUSTOMER");
        jl_datacustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_datacustomerMouseClicked(evt);
            }
        });

        jl_updateadmin.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jl_updateadmin.setForeground(new java.awt.Color(243, 153, 153));
        jl_updateadmin.setText("UPDATE ADMIN");
        jl_updateadmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_updateadminMouseClicked(evt);
            }
        });

        jl_products.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jl_products.setForeground(java.awt.Color.white);
        jl_products.setText("PRODUCTS");
        jl_products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_productsMouseClicked(evt);
            }
        });

        jl_category.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jl_category.setForeground(new java.awt.Color(243, 153, 153));
        jl_category.setText("CATEGORY");
        jl_category.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_categoryMouseClicked(evt);
            }
        });

        jl_supplier.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jl_supplier.setForeground(new java.awt.Color(243, 153, 153));
        jl_supplier.setText("SUPPLIER");
        jl_supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_supplierMouseClicked(evt);
            }
        });

        btn_logout.setBackground(new java.awt.Color(255, 251, 237));
        btn_logout.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(231, 50, 50));
        btn_logout.setText("LOGOUT");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jl_jam))
                            .addComponent(jl_tanggal)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jl_home)
                            .addComponent(jl_datacustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jl_updateadmin)
                            .addComponent(jl_products)
                            .addComponent(jl_category)
                            .addComponent(jl_supplier)
                            .addComponent(btn_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jl_tanggal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_jam)
                .addGap(27, 27, 27)
                .addComponent(jl_home)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_datacustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_updateadmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_products)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_category)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_supplier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_logout)
                .addGap(23, 23, 23))
        );

        jPanel2.setBackground(new java.awt.Color(255, 251, 237));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(231, 50, 50));
        jLabel2.setText("MANAGE PRODUCTS");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("PRODUCT ID");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("PRODUCT NAME");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel5.setText("CATEGORY");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel6.setText("QUANTITY");

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel7.setText("PRICE");

        tf_proid.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N

        tf_proname.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N

        tf_quantity.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        tf_quantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_quantityKeyTyped(evt);
            }
        });

        tf_price.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        tf_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_priceKeyTyped(evt);
            }
        });

        cb_category.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N

        btn_add.setBackground(new java.awt.Color(231, 50, 50));
        btn_add.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_add.setForeground(java.awt.Color.white);
        btn_add.setText("ADD");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_edit.setBackground(new java.awt.Color(231, 50, 50));
        btn_edit.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_edit.setForeground(java.awt.Color.white);
        btn_edit.setText("EDIT");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(231, 50, 50));
        btn_delete.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_delete.setForeground(java.awt.Color.white);
        btn_delete.setText("DELETE");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_clear.setBackground(new java.awt.Color(231, 50, 50));
        btn_clear.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_clear.setForeground(java.awt.Color.white);
        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        tb_list.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tb_list.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        tb_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCT ID", "PRODUCT NAME", "CATEGORY", "QUANTITY", "PRICE", "SUPPLIER"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_list.setRowHeight(25);
        tb_list.setShowGrid(true);
        tb_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_listMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_list);

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(231, 50, 50));
        jLabel8.setText("PRODUCTS LIST");

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel9.setText("SUPPLIER");

        cb_supplier.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N

        jl_close.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jl_close.setForeground(java.awt.Color.red);
        jl_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/close_merah.10px.png"))); // NOI18N
        jl_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_proname, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cb_category, 0, 140, Short.MAX_VALUE)
                                    .addComponent(tf_proid))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tf_price)
                                            .addComponent(tf_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cb_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(btn_delete)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(129, 129, 129)
                .addComponent(jl_close)
                .addGap(18, 18, 18))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jl_close)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tf_proid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tf_proname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(cb_category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tf_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tf_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cb_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_add)
                        .addComponent(btn_edit))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_delete)))
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        if(tf_proid.getText().isEmpty()|| tf_proname.getText().isEmpty()|| 
                tf_quantity.getText().isEmpty()|| tf_price.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Fill all the Fields");
        }
        else{
            try{
                Con = (Connection) (DriverManager.getConnection("jdbc:mysql://localhost:3306/adanadb","root",""));
                PreparedStatement add = Con.prepareStatement("insert into product (proid,proname,category,quantity,price,"
                        + "supplier) values (?,?,?,?,?,?)");
                add.setInt(1, Integer.valueOf(tf_proid.getText()));
                add.setString(2, tf_proname.getText());
                add.setString(3, cb_category.getSelectedItem().toString());
                add.setInt(4, Integer.valueOf(tf_quantity.getText()));
                add.setInt(5, Integer.valueOf(tf_price.getText()));
                add.setString(6, cb_supplier.getSelectedItem().toString());
                int row = add.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data added Successfully");
                tf_proid.setText("");
                tf_proname.setText("");
                tf_quantity.setText("");
                tf_price.setText("");
                tf_proname.requestFocus();
                isidataproduct();
            }catch(SQLException e){
            }
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tb_list.getModel();
        int selectedIndex = tb_list.getSelectedRow();
        if(tf_proid.getText().isEmpty()|| tf_proname.getText().isEmpty()|| tf_quantity.getText().isEmpty()||
                tf_price.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Fill all the Fields");
        }
        else{
            try{
                int id = Integer.parseInt(model.getValueAt(selectedIndex, 0).toString());
                Con = (Connection) (DriverManager.getConnection("jdbc:mysql://localhost:3306/adanadb","root",""));
                Pst = Con.prepareStatement("Update adanadb.product set proname=?, category=?, quantity=?,"
                        + "price=?, supplier=? where proid=?");
                Pst.setString(1, tf_proname.getText());
                Pst.setString(2, cb_category.getSelectedItem().toString());
                Pst.setInt(3, Integer.valueOf(tf_quantity.getText()));
                Pst.setInt(4, Integer.valueOf(tf_price.getText()));
                Pst.setString(5, cb_supplier.getSelectedItem().toString());
                Pst.setInt(6, id);
                Pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Updated Successfully");
                isidataproduct();
            }catch(SQLException e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tb_list.getModel();
        int selectedIndex = tb_list.getSelectedRow();
        if(tf_proid.getText().isEmpty()|| tf_proname.getText().isEmpty()|| tf_quantity.getText().isEmpty()||
                tf_price.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Select the Data You Want to Delete");
        }
        else{
            try{
                int id = Integer.parseInt(model.getValueAt(selectedIndex, 0).toString());
                Con = (Connection) (DriverManager.getConnection("jdbc:mysql://localhost:3306/adanadb","root",""));
                Pst = Con.prepareStatement("Delete from product where proid=?");
                Pst.setInt(1, id);
                Pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Deleted Successfully");
                tf_proid.setText("");
                tf_proname.setText("");
                tf_quantity.setText("");
                tf_price.setText("");
                isidataproduct();
            }catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        tf_proid.setText("");
        tf_proname.setText("");
        tf_quantity.setText("");
        tf_price.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed

    private void tb_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_listMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tb_list.getModel();
        int Myindex = tb_list.getSelectedRow();
        tf_proid.setText(model.getValueAt(Myindex, 0).toString());
        tf_proname.setText(model.getValueAt(Myindex, 1).toString());
        tf_price.setText(model.getValueAt(Myindex, 4).toString());
        tf_quantity.setText(model.getValueAt(Myindex, 3).toString());
    }//GEN-LAST:event_tb_listMouseClicked

    private void tf_quantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_quantityKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_tf_quantityKeyTyped

    private void tf_priceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_priceKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_tf_priceKeyTyped

    private void jl_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_homeMouseClicked
        // TODO add your handling code here:
        Admin ad = new Admin();
        ad.setVisible(true);
        dispose();
    }//GEN-LAST:event_jl_homeMouseClicked

    private void jl_datacustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_datacustomerMouseClicked
        // TODO add your handling code here:
        DataCustomer dc = new DataCustomer();
        dc.setVisible(true);
        dispose();
    }//GEN-LAST:event_jl_datacustomerMouseClicked

    private void jl_updateadminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_updateadminMouseClicked
        // TODO add your handling code here:
        UpdateAdmin ua = new UpdateAdmin();
        ua.setVisible(true);
        dispose();
    }//GEN-LAST:event_jl_updateadminMouseClicked

    private void jl_productsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_productsMouseClicked
        // TODO add your handling code here:
        Products pro = new Products();
        pro.setVisible(true);
        dispose();
    }//GEN-LAST:event_jl_productsMouseClicked

    private void jl_categoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_categoryMouseClicked
        // TODO add your handling code here:
        Category ca = new Category();
        ca.setVisible(true);
        dispose();
    }//GEN-LAST:event_jl_categoryMouseClicked

    private void jl_supplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_supplierMouseClicked
        // TODO add your handling code here:
        Supplier su = new Supplier();
        su.setVisible(true);
        dispose();
    }//GEN-LAST:event_jl_supplierMouseClicked

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        int jawab = JOptionPane.showOptionDialog(this,"Are You Sure Want to Logout?","Logout",
            JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE, null, null, null);
        if(jawab == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Back To Login");
            LoginAdmin la = new LoginAdmin();
            la.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void jl_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_closeMouseClicked
        // TODO add your handling code here:
        int jawab = JOptionPane.showOptionDialog(this,"Are You Sure Want to Exit?","Exit",
            JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE, null, null, null);
        if(jawab == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Program Stop");
            System.exit(0);
        }
    }//GEN-LAST:event_jl_closeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Products().setVisible(true);
            }
        });
    }
    
    public void isidataproduct(){
        int no;
        try{
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/adanadb","root","");
            St = Con.createStatement();
            Rs = St.executeQuery("select * from adanadb.product");
            ResultSetMetaData RSMD = (ResultSetMetaData) Rs.getMetaData();
            no = RSMD.getColumnCount();
            DefaultTableModel DFT = (DefaultTableModel) tb_list.getModel();
            DFT.setRowCount(0);
            while (Rs.next()) {
                Vector v = new Vector();
                for (int i = 1; i <= no; i++) {
                    v.add(Rs.getString("proid"));
                    v.add(Rs.getString("proname"));
                    v.add(Rs.getString("category"));
                    v.add(Rs.getString("quantity"));
                    v.add(Rs.getString("price"));
                    v.add(Rs.getString("supplier"));
                }
                DFT.addRow(v);
            }
        } catch (Exception e) {
        }
    }
    
    public Products(String username){
        initComponents();
    }
    
    private void GetCat(){
        try{
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/adanadb","root","");
            St = Con.createStatement();
            String query = "select * from adanadb.category";
            Rs = St.executeQuery(query);
            while(Rs.next()){
                String Mycat = Rs.getString("CatName");
                cb_category.addItem(Mycat);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void GetSup(){
        try{
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/adanadb","root","");
            St = Con.createStatement();
            String query = "select * from adanadb.supplier";
            Rs = St.executeQuery(query);
            while(Rs.next()){
                String Mysup = Rs.getString("SupCom");
                cb_supplier.addItem(Mysup);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    public void Tampil_Jam(){
        ActionListener taskPerformer = new ActionListener() {
        @Override
            public void actionPerformed(ActionEvent evt) {
            String nol_jam = "", nol_menit = "",nol_detik = "";
 
            java.util.Date dateTime = new java.util.Date();
            int nilai_jam = dateTime.getHours();
            int nilai_menit = dateTime.getMinutes();
            int nilai_detik = dateTime.getSeconds();
 
            if(nilai_jam <= 9) nol_jam= "0";
            if(nilai_menit <= 9) nol_menit= "0";
            if(nilai_detik <= 9) nol_detik= "0";
 
            String jam = nol_jam + Integer.toString(nilai_jam);
            String menit = nol_menit + Integer.toString(nilai_menit);
            String detik = nol_detik + Integer.toString(nilai_detik);
 
            jl_jam.setText(jam+":"+menit+":"+detik+"");
            }
        };
    new Timer(1000, taskPerformer).start();
    }   
 
    public void Tampil_Tanggal() {
    java.util.Date tglsekarang = new java.util.Date();
    SimpleDateFormat smpdtfmt = new SimpleDateFormat("dd MMMMMMMMM yyyy", Locale.getDefault());
    String tanggal = smpdtfmt.format(tglsekarang);
    jl_tanggal.setText(tanggal);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_logout;
    private javax.swing.JComboBox<String> cb_category;
    private javax.swing.JComboBox<String> cb_supplier;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jl_category;
    private javax.swing.JLabel jl_close;
    private javax.swing.JLabel jl_datacustomer;
    private javax.swing.JLabel jl_home;
    private javax.swing.JLabel jl_jam;
    private javax.swing.JLabel jl_products;
    private javax.swing.JLabel jl_supplier;
    private javax.swing.JLabel jl_tanggal;
    private javax.swing.JLabel jl_updateadmin;
    private javax.swing.JTable tb_list;
    private javax.swing.JTextField tf_price;
    private javax.swing.JTextField tf_proid;
    private javax.swing.JTextField tf_proname;
    private javax.swing.JTextField tf_quantity;
    // End of variables declaration//GEN-END:variables
}
